### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by pstetz** [youngmoney/dot#1]
Hey Taylor, are you gettting this?  I'm in Dallas right now on a 17hr layover.  The place is huuge, not really bored because the airport's a small city.  They also have free computers and nice chairs and desks.  Your website inspired me so I think I'll check out codeacademy to kill some time

Communicating this way might work since github's not blocked in China.  Anyways thanks for driving me to and from Berkeley!

**Comment by youngmoney** [comment]
I've created a new repository pat-chat and pat-chat-private (use the private one if you can!)
